import React from "react";
import Forms from "@chappy/components/Forms";
import {PasswordComplexityRequirements} from '@chappy/components/PasswordComplexityRequirements';
import route from "@chappy/utils/route";
/**
 * Render component for password reset view.
 * 
 * @property {object} user The user whose password to be reset.
 * @property {array} errors The errors generated by the users model.
 * @param {InputProps} param0 
 * @returns {HTMLDivElement} Component for password reset view.
 */
function UpdatePassword({user, errors}) {

    return (
        <div className="row align-items-center justify-content-center">
            <div className="col-md-6 bg-light p-3">
                <h1 className="text-center">Change Password for {user.username}</h1>
                <hr />
                <PasswordComplexityRequirements />
                <form className="form" action="" method="post">
                    <Forms.CSRF />
                    <Forms.DisplayErrors errors={errors}/>
                    <Forms.Input 
                        type="password"
                        label="Current Password"
                        name="current_password"
                        value=""
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-3"}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Password"
                        name="password"
                        value=""
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-3"}}
                    />
                    <Forms.Input 
                        type="password"
                        label="Confirm Password"
                        name="confirm"
                        value=""
                        inputAttrs={{className: "form-control input-sm"}}
                        divAttrs={{className: "form-group mb-4"}}
                    />
                    <div className="col-md-12 text-end">
                        <a href={route("profile")} className="btn btn-default">Cancel</a>
                        <Forms.SubmitTag label="Update" inputAttrs={{className: "btn btn-primary"}} />
                    </div>
                </form>
            </div>
        </div>
    );
}        
export default UpdatePassword;